name: Build Release

on:
  push:
    tags:
      - 'v*' # 当推送版本标签时触发
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x]
        include:
          - os: ubuntu-latest
            platform: linux
            artifact_name: nas-system-linux
            asset_name: nas-system-linux-x64
          - os: windows-latest
            platform: win32
            artifact_name: nas-system-windows.exe
            asset_name: nas-system-windows-x64
          - os: macos-latest
            platform: darwin
            artifact_name: nas-system-macos
            asset_name: nas-system-macos-x64

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm install -g pkg

      - name: Build TypeScript
        run: npm run build

      - name: Package application
        run: |
          pkg . --targets node18-${{ matrix.platform }}-x64 --output dist/${{ matrix.artifact_name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: dist/${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nas-system-linux-x64/nas-system-linux
            nas-system-windows-x64/nas-system-windows.exe
            nas-system-macos-x64/nas-system-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 